language: node_js
after_success:
  - $(npm bin)/set-up-ssh --key "${encrypted_02cb1b6d7df1_key}"
      --iv "${encrypted_02cb1b6d7df1_iv}"
      --path-encrypted-key .travis-github-deploy-key.enc
  - $(npm bin)/update-branch --commands 'npm run build'
      --commit-message "Update gh-pages @ ${TRAVIS_COMMIT}"
      --directory 'dist'
      --distribution-branch 'gh-pages'
      --source-branch 'main'
git:
  depth: 1
branches:
  only:
    - main
env:
  global:
    secure: "wKIDiTzMadGINGEt4Tf9yzALBjGzJEmWDmcGgMIGGO2oh/y6hsqge7HbQ+wWngXf/YD/AmCBSU1P6NEQs/qsg7HSfUrwTcHG9xwKzn5hV0KfSLVujFLPUBIDUl4K1dHlubSE358UNwgnE3MsFg+j+Z7gLqOaYwSNb0csH8+QHspv4EN7sqw3jzsHGOhtk6LJHXfKB6ENA4prhF9HluXjA3jbMCy+u4GwPS2NR8S0kZE2NKJKi/mPhOoVhc2elz047E49+eDf/Yca7LRDfVBbCrAdObEz6xkuCrahLLkwAmW9Snex+3XkG0PUqs7S+0X/gM0GzF/1zhGOTsTNiL8gF1e0yP5sj3ph49UG/VHwFoPQrlyrPQHgykZ3PIGfszqeQy1Czyixv7IAOBc8kSu65JXhZL7wKt8X7G7/zXmhiEv+YbDwpZr61A7TuC3Iae0+WZZ9cxeMLUXFDa2cFBQ2CnL24SCOQPjO1+L6+v+BPr+3gRSqJlqK+jIxcK9Xc2iIj8p4zpw1yhxA/7pDAYdURJa6d/eNiqCpUAjIvnK4pDX/+iiwFgbz+9qQA6uZUEF96ObgzpKY6FZZp+jq1m8l3+EHrw1scNBvZCi/hshskz6i25mDh8tMU9+gvnRqUSsZF2+m5NIyfxSR/Gq5XxvRiZ4if+40p1AOzt+WtLLZmQk="
